apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: voctoweb
  annotations:
    github.com/project-slug: voc/voctoweb
spec:
  type: url
  targets:
    - ./system.yaml
    - ./app/backstage.yml
    - ./app/controllers/public/backstage.yml
    - ./app/controllers/api/backstage.yml
    - ./app/graphql/backstage.yml